SELECT DISTINCT AS_ENTITY_ROLE.ONLINE_ENTITY_ID 
FROM DN1PCOMN.AS_USER_PROFILE AS_USER_PROFILE INNER JOIN DN1PCOMN.AS_ENTITY_ROLE AS_ENTITY_ROLE 
ON AS_USER_PROFILE.ENTITY_ID = AS_ENTITY_ROLE.ENTITY_ID 
INNER JOIN DN1PCOMN.AS_ROLE_RELATION AS_ROLE_RELATION
ON AS_ENTITY_ROLE.ROLE_ID = AS_ROLE_RELATION.ROLE_ID WHERE AS_USER_PROFILE.USER_ID = 'DNSERVER' 
AND AS_USER_PROFILE.CUST_ID = 'GTWY' AND (((AS_ROLE_RELATION.STS_TRAN_COL_NAME LIKE 'PROC_GRP%')
AND (AS_ENTITY_ROLE.ONLINE_ENTITY_ID = 'NYCE' OR AS_ENTITY_ROLE.ONLINE_ENTITY_ID = 'NYCE'))   OR
((AS_ROLE_RELATION.STS_TRAN_COL_NAME LIKE 'PROC_ID%') AND (AS_ENTITY_ROLE.ONLINE_ENTITY_ID = 'INT797' 
OR AS_ENTITY_ROLE.ONLINE_ENTITY_ID = 'PRC770')) OR ((AS_ROLE_RELATION.STS_TRAN_COL_NAME LIKE 'INST%') AND
(AS_ENTITY_ROLE.ONLINE_ENTITY_ID = '695695697' OR AS_ENTITY_ROLE.ONLINE_ENTITY_ID = '841510115')) OR
(AS_ROLE_RELATION.STS_TRAN_COL_NAME = 'NET_TERM_ID' 
AND AS_ENTITY_ROLE.ONLINE_ENTITY_ID = 'AF6950') OR (AS_ROLE_RELATION.STS_TRAN_COL_NAME = ' '))
